<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.universal.iot</groupId>
    <artifactId>cn-universal-plugins</artifactId>
    <version>1.5-SNAPSHOT</version>
  </parent>
  <description>java实现产品驱动，主要针对超复杂协议（如门锁）和平台互通的情况</description>
  <artifactId>nexiot-jar-deiver-extend-plugins</artifactId>
  <properties>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <!-- 核心框架依赖 -->
    <dependency>
      <groupId>cn.universal.iot</groupId>
      <artifactId>cn-universal-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- 通用依赖 -->
    <dependency>
      <groupId>cn.universal.iot</groupId>
      <artifactId>cn-universal-common</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- 数据持久化依赖 -->
    <dependency>
      <groupId>cn.universal.iot</groupId>
      <artifactId>cn-universal-persistence</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- 设备管理依赖 -->
    <dependency>
      <groupId>cn.universal.iot</groupId>
      <artifactId>cn-universal-dm</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- Spring Boot Web -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <!-- 工具类 -->
    <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-all</artifactId>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>


</project>